### ISSUE TITLE
Unable to sign counterfactual contract address

### ISSUE THREAD

**Issue by nfts2me** [AmbireTech/signature-validator#7]
![image](https://user-images.githubusercontent.com/109629895/233059590-7d9f5291-46bf-46fe-9570-fe7350c204fa.png)

I'm getting this error when trying to sign a message.
Doesnt' Ambire support [ERC-6492](https://eips.ethereum.org/EIPS/eip-6492): Signature verification for pre-deploy counterfactual contracts?

**Comment by TRtomasz** [comment]
Hi @nfts2me it does, but it has not been yet deployed to the production, you can try it out here http://wallet.ambire.com/staging.

**Comment by nfts2me** [comment]
Thank you!
