### ISSUE TITLE
verifyMessage does not work with undeployed smart accounts.

### ISSUE THREAD

**Issue by vukhaihoan** [AmbireTech/signature-validator#8]

**Comment by vukhaihoan** [comment]
@ambire/signature-validator@1.3.1

**Comment by Ivshti** [comment]
not a bug, this is how EIP-1271 works.

However, verifyMessage will work with undeployed contracts if the signer implements [EIP-6492](https://eips.ethereum.org/EIPS/eip-6492)

**Comment by vukhaihoan** [comment]
> not a bug, this is how EIP-1271 works.
> 
> However, verifyMessage will work with undeployed contracts if the signer implements [EIP-6492](https://eips.ethereum.org/EIPS/eip-6492)

How do I know if the signer implements [EIP-6492](https://eips.ethereum.org/EIPS/eip-6492)
