### ISSUE TITLE
Proposal - Support for viem client in Verify Message

### ISSUE THREAD

**Issue by Aman035** [AmbireTech/signature-validator#9]
Currently `verifyMessage` only supports a ethers provider as input. 
Adding support for viem client will allow usage of this package with viem too.
More on ethers to viem migration - [here](https://viem.sh/docs/ethers-migration.html#provider-%E2%86%92-client)

**Comment by Ivshti** [comment]
@Aman035 can you PR this?

**Comment by Aman035** [comment]
Hey @Ivshti added the pr #12

**Comment by Ivshti** [comment]
@Aman035 fantastic! I have some dependency bloat concerns but other than that I'm willing to merge

**Comment by Ivshti** [comment]
implemented via #12
